export const FETCH_IMAGE_REQUESTED = 'app/Home/FETCH_IMAGE_REQUESTED';
export const FETCH_IMAGE_SUCCEEDED = 'app/Home/FETCH_IMAGE_SUCCEEDED';
export const FETCH_IMAGE_FAILED = 'app/Home/FETCH_IMAGE_FAILED';
