export const FETCH_IMAGE_REQUESTED = 'app/Home/FETCH_IMAGE_REQUESTED';
export const FETCH_IMAGE_SUCCEEDED = 'app/Home/FETCH_IMAGE_SUCCEEDED';
export const FETCH_IMAGE_FAILED = 'app/Home/FETCH_IMAGE_FAILED';

export const INITIAL_DATA_REQUESTED = 'app/Home/INITIAL_DATA_REQUESTED';
export const INITIAL_DATA_SUCCEEDED = 'app/Home/INITIAL_DATA_SUCCEEDED';
export const INITIAL_DATA_FAILED = 'app/Home/INITIAL_DATA_FAILED';

export const FETCH_BREEDS_REQUESTED = 'app/Home/FETCH_BREEDS_REQUESTED';
export const FETCH_BREEDS_SUCCEEDED = 'app/Home/FETCH_BREEDS_SUCCEEDED';
export const FETCH_BREEDS_FAILED = 'app/Home/FETCH_BREEDS_FAILED';

export const UPDATE_SELECTED_BREED = 'app/Home/UPDATE_SELECTED_BREED';
